version: "3"
services: 
  freegames:
    build: .
    environment: 
      EPIC_EMAIL:
      EPIC_PASSWORD: 
      EPIC_TFA_TOKEN:
      USER_AGENT: 'Mozilla/5.0 (X11; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0'